# Generated by Django 3.0.4 on 2020-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiotelescope', '0002_auto_20200318_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountstatus',
            name='scanProgress',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mountstatus',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
